
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nevbar from './Component/Nevbar.jsx'
import Fixedicons from './Component/Fixedicons.jsx'
import Fixedupicons from './Component/Fixedupicons.jsx'
import Fixedcalliocns from './Component/Fixedcallicons.jsx'
import 'aos/dist/aos.css'
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from './Component/Footer.jsx'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "INDIADEALS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Nevbar />
        
        {children}
        <Fixedicons />
        <Fixedcalliocns />
        <Fixedupicons />
        <Footer />
      </body>
    </html>
  );
}
